// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Book_Store.Data;

#nullable disable

namespace Super_Book_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230516062831_Create_Table_NhanVien")]
    partial class Create_Table_NhanVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Super_Book_Store.Models.BookType", b =>
                {
                    b.Property<string>("BookID")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.HasIndex("LanguageID");

                    b.ToTable("BookType");
                });

            modelBuilder.Entity("Super_Book_Store.Models.KhachHang", b =>
                {
                    b.Property<string>("CodeKhachHang")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KhachHangName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CodeKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("Super_Book_Store.Models.Kho", b =>
                {
                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<int>("NhapKho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TonKho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XuatKho")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookName");

                    b.ToTable("Kho");
                });

            modelBuilder.Entity("Super_Book_Store.Models.Language", b =>
                {
                    b.Property<string>("LanguageID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Super_Book_Store.Models.NhaXuatBan", b =>
                {
                    b.Property<string>("NXBName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NXBName");

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("Super_Book_Store.Models.NhanVien", b =>
                {
                    b.Property<string>("NhanVienID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanVienName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NhanVienID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Super_Book_Store.Models.BookType", b =>
                {
                    b.HasOne("Super_Book_Store.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
