// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Super_Book_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230519050051_Create_Table_BookType")]
    partial class Create_Table_BookType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Super_Book_Store.Models.BookType", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookNameID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookTypeNew")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.HasIndex("BookNameID");

                    b.HasIndex("LanguageID");

                    b.ToTable("BookType");
                });

            modelBuilder.Entity("Super_Book_Store.Models.Kho", b =>
                {
                    b.Property<string>("BookID")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BookStoreExists")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberbBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.ToTable("Khoss");
                });

            modelBuilder.Entity("Super_Book_Store.Models.Language", b =>
                {
                    b.Property<string>("LanguageID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Super_Book_Store.Models.BookType", b =>
                {
                    b.HasOne("Super_Book_Store.Models.Kho", "Kho")
                        .WithMany()
                        .HasForeignKey("BookNameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Super_Book_Store.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("Language");
                });
#pragma warning restore 612, 618
        }
    }
}
