// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Super_Book_Store.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230515162756_Create_Table_Kho")]
    partial class Create_Table_Kho
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Super_Book_Store.Models.Kho", b =>
                {
                    b.Property<string>("BookName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BookStoreExists")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExportBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberbBook")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BookName");

                    b.ToTable("Khoss");
                });
#pragma warning restore 612, 618
        }
    }
}
